/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package healthapp;

/**
 *
 * @author siddarth
 */
public class InformationBp extends javax.swing.JFrame {

    /**
     * Creates new form InformationBp
     */
    public InformationBp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("<HTML>\nHYPERTENSION<HTML>\n\n<HTML>Also known as high blood pressure, hypertension is the most common cardiovascular disease.\nBlood pressure is the force of blood pushing against your artery walls as it goes through your body\nHigh blood pressure can hurt your arteries and lead to life-threatening conditions like heart disease and stroke.\nSYMPTOMS\nSevere headache\nFatigue or confusion\nVision problems\nChest pain\nDifficulty breathing\nIrregular heartbeat\nBlood in the urine\nPounding in your chest, neck, or ears\nDIAGNOSIS\nBlood pressure is measured using sphygmomanometer .The first, the higher of the two, is your systolic pressure. That's the force in the arteries when the heart beats. The second number is your diastolic pressure, or the pressure in the arteries when the heart rests between beats.\n\n\n\n\n\n\n\nIt's also more common in people who are:\n\nAfrican-American\nOlder than 55\nOverweight\nInactive\nHeavy alcohol drinkers\nSmokers\nTREATMENT\nThe goal of hypertension treatment is to lower high blood pressure and protect important organs, like the brain, heart, and kidneys from damage.\nlifestyle modifications, such as eating a healthier diet, quitting smoking, and getting more exercise.\nDRUGS\nDrugs to Treat High Blood Pressure\nThere are several types of drugs used to treat high blood pressure, including:\n\nAngiotensin-converting enzyme (ACE) inhibitors\nAngiotensin II receptor blockers (ARBs)\nDiuretics\nBeta-blockers\nCalcium channel blockers\nAlpha-blockers\nAlpha-agonists\nRenin inhibitors\nCombination medications\nDiuretics are often recommended as the first line of therapy for most people who have high blood pressure.\n<HTML>");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setEnabled(false);
        jLabel3.setFocusCycleRoot(true);

        jLabel4.setText("<HTML> HYPERTENSION                                                                                                                                                                                                                 Also known as high blood pressure, hypertension is the most common cardiovascular disease. Blood pressure is the force of blood pushing against your artery walls as it goes through your body High blood pressure can hurt your arteries and lead to life-threatening conditions like heart disease and stroke.<HTML> ");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        jLabel2.setText("INFORMATION");

        jTextPane1.setText("HYPERTENSION\n\nAlso known as  high blood pressure , hypertension is the most common cardiovascular disease. Blood Pressure is the force of blood pushing against your artilery walls as it get through your body.\n\nHigh Blood pressure can hurt your artileries and lead to life threatning conditions like heart disease and stroke.\n\nSYMPTOMS\n\nSevere Headache \nFatigue or confusion\nvision problems \nChest pain \nDifficulty breathing \nIrregular heartbeat\nBlood in the urine\nPounding in your chest, neck or ears\n\nDIAGONOSIS\n\nBlood pressure is measured using sphygmomanometer the first, the higher of the two is your systolicpressure. That's is the force in the arteries when the heart beat. The Second number is your Diastolic pressure, or the pressure in the arteries when the heart rest between beats. It is also more common in people who are\n African/ American\nOlder than 55\nOwerweight\nInactive\nHeavy alcohol drinkers\nSmokers\n\nTREATMENT\n\nThe goal of hypertension is two lower high blood pressure and protect important organs , like the brain , heart , and kidneys from damage.\n\nLifestyle modifications, eating a healthier diet , quitiin g smoking , and getting more exercise.\n\nDRUGS\n\nDrugs to treat high blood Pressure:\n\nThere are several types of drugs use to treat high blood pressure , including :\n\nAngiotensin-converting enzyme(ACE) inhibitors\nAngiotensin II receptors blocker(ARBs) \nDiuretics\nBeta-blockers\nCalcium Channel blockers\nAlfa Blockers\nAlfa Agonist\nRenin inhibitors\nCombinational Medicines\nDueretics are often recommended as the first line of therapy for most people who have high blood pressure.\n\n\n");
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(719, 719, 719)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       BloodPressure bp = new BloodPressure();
       bp.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformationBp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformationBp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformationBp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformationBp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformationBp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
